channels:
- conda-forge
dependencies:
- python=3.11.0
- pip<=25.3
- pip:
  - mlflow==2.18.0
  - cloudpickle==3.1.2
  - numpy==1.26.3
  - pandas==2.2.0
  - psutil==5.9.8
  - pyarrow==15.0.0
  - scikit-learn==1.7.2
  - scipy==1.12.0
name: mlflow-env
